### ISSUE TITLE
where to find the "DA_model/model_uniESM2_650M_DA_combo_e30_lrsWarmupCosine" file?

### ISSUE THREAD

**Issue by liamxg** [TheSatoLab/CoVFit#1]
Dear @AdamInTokyo,

Could I know where to find the "DA_model/model_uniESM2_650M_DA_combo_e30_lrsWarmupCosine" and "facebook/esm2_t33_650M_UR50D" files?

Thanks.

**Comment by AdamInTokyo** [comment]
Hi Liam. Thanks for your interest in CoVFit. 

The "facebook/esm2_t33_650M_UR50D" string is the name of the base 650 million parameter ESM2 model which should be automatically downloaded by the Hugging Face transformers module when using the AutoModel.from_pretrained() method or similar. 

The "DA_model/model_uniESM2_650M_DA_combo_e30_lrsWarmupCosine" is the model that results from the  Domain_Adaptation_training.py script in the Domain Adaptation section. There is no model file available to download here at the moment, so you can train it yourself if you assemble the dataset from the paper. The model is too large for us to host on github directly, but let me look into it, and I'll get back with you.

**Comment by AdamInTokyo** [comment]
OK, the DA model, i.e. ESM2<sub>coroniviridae</sub>, is now available to be downloaded from Zenodo. You'll find the link in the ReadMe.md file in the [Domain Adaptation](https://github.com/TheSatoLab/CoVFit/tree/main/Domain%20Adaptation) section. Note that it will be called `model_ESM2_coronaviridae` instead of `model_uniESM2_650M_DA_combo_e30_lrsWarmupCosine`.

**Comment by liamxg** [comment]
Dear @AdamInTokyo,

Thanks. that's really helpful to me.
